### ISSUE TITLE
bug: no longer possible to pass multiple args

### ISSUE THREAD

**Issue by muratso** [sudo-bot/action-docker-compose#2]
Due to the changes in the commits 1ef7f662ec7cdf9223808e4578d0d8304eb81c0f and 5e3eedc7cd8117bb1836adbb6eecd6fabc0391cc and the way docker handles arguments, it's no longer possible to have something like 
```yml
- name: run docker-compose
    uses: sudo-bot/action-docker-compose@latest
    with:
        # https://docs.docker.com/compose/reference/overview/
        cli-args: "up -d"
```
